# Generated by Django 4.1.2 on 2022-11-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biblioteca", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registro",
            name="tipo",
            field=models.CharField(max_length=15),
        ),
    ]
