# Generated by Django 4.1.2 on 2022-11-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biblioteca", "0003_alter_registro_material_alter_registro_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="id",
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
